<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Régression linéaire | Annalyse de données</title>
  <meta name="description" content="Ce projet d’analyse de donnés consiste à l’explication de différentes manières le nombre de crime aux Etats-Unis." />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Régression linéaire | Annalyse de données" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Ce projet d’analyse de donnés consiste à l’explication de différentes manières le nombre de crime aux Etats-Unis." />
  <meta name="github-repo" content="AODiakite/Data-Analysis" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Régression linéaire | Annalyse de données" />
  
  <meta name="twitter:description" content="Ce projet d’analyse de donnés consiste à l’explication de différentes manières le nombre de crime aux Etats-Unis." />
  

<meta name="author" content="Abdoul Oudouss Diakite, Othmane ETTADLAOUI" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="principal-component-analysis-and-factor-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#description-du-jeu-de-données"><i class="fa fa-check"></i>Description du jeu de données</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#source-des-données"><i class="fa fa-check"></i>Source des données</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="linearModel.html"><a href="linearModel.html"><i class="fa fa-check"></i><b>1</b> Régression linéaire</a>
<ul>
<li class="chapter" data-level="1.1" data-path="linearModel.html"><a href="linearModel.html#introduction-1"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="linearModel.html"><a href="linearModel.html#application-de-la-régression-linéaire-simple"><i class="fa fa-check"></i><b>1.2</b> Application de la régression linéaire simple</a>
<ul>
<li class="chapter" data-level="" data-path="linearModel.html"><a href="linearModel.html#corrélation"><i class="fa fa-check"></i>Corrélation</a></li>
<li class="chapter" data-level="" data-path="linearModel.html"><a href="linearModel.html#nuage-de-points"><i class="fa fa-check"></i>Nuage de points</a></li>
<li class="chapter" data-level="" data-path="linearModel.html"><a href="linearModel.html#entraînement-de-modèle-droite-de-régression"><i class="fa fa-check"></i>Entraînement de modèle &amp; Droite de régression</a></li>
<li class="chapter" data-level="" data-path="linearModel.html"><a href="linearModel.html#prédiction"><i class="fa fa-check"></i>Prédiction</a></li>
<li class="chapter" data-level="" data-path="linearModel.html"><a href="linearModel.html#graphes-des-résidus"><i class="fa fa-check"></i>Graphes des résidus</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="linearModel.html"><a href="linearModel.html#application-de-la-régression-linéaire-multiple"><i class="fa fa-check"></i><b>1.3</b> Application de la régression linéaire multiple</a>
<ul>
<li class="chapter" data-level="" data-path="linearModel.html"><a href="linearModel.html#entraînement-de-modèle"><i class="fa fa-check"></i>Entraînement de modèle</a></li>
<li class="chapter" data-level="" data-path="linearModel.html"><a href="linearModel.html#graphes-de-régression"><i class="fa fa-check"></i>Graphes de régression</a></li>
<li class="chapter" data-level="" data-path="linearModel.html"><a href="linearModel.html#prédiction-1"><i class="fa fa-check"></i>Prédiction</a></li>
<li class="chapter" data-level="1.3.1" data-path="linearModel.html"><a href="linearModel.html#graphe-des-résidus"><i class="fa fa-check"></i><b>1.3.1</b> Graphe des résidus</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="principal-component-analysis-and-factor-analysis.html"><a href="principal-component-analysis-and-factor-analysis.html"><i class="fa fa-check"></i><b>2</b> Principal Component Analysis and Factor Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="principal-component-analysis-and-factor-analysis.html"><a href="principal-component-analysis-and-factor-analysis.html#sélection-des-variables-numériques"><i class="fa fa-check"></i>Sélection des variables numériques</a></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-and-factor-analysis.html"><a href="principal-component-analysis-and-factor-analysis.html#application-de-la-fonction-pca"><i class="fa fa-check"></i>Application de la fonction PCA</a></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-and-factor-analysis.html"><a href="principal-component-analysis-and-factor-analysis.html#pourcentage-dexplication"><i class="fa fa-check"></i>Pourcentage d’explication</a></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-and-factor-analysis.html"><a href="principal-component-analysis-and-factor-analysis.html#graphiques-de-corrélation-des-variables"><i class="fa fa-check"></i>Graphiques de corrélation des variables</a></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-and-factor-analysis.html"><a href="principal-component-analysis-and-factor-analysis.html#graphes-des-individus"><i class="fa fa-check"></i>Graphes des individus</a></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-and-factor-analysis.html"><a href="principal-component-analysis-and-factor-analysis.html#biplot-individus-et-variables"><i class="fa fa-check"></i>Biplot individus et variables</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lanalyse-de-la-variance.html"><a href="lanalyse-de-la-variance.html"><i class="fa fa-check"></i><b>3</b> L’analyse de la variance</a>
<ul>
<li class="chapter" data-level="" data-path="lanalyse-de-la-variance.html"><a href="lanalyse-de-la-variance.html#sélection-des-données"><i class="fa fa-check"></i>Sélection des données</a></li>
<li class="chapter" data-level="" data-path="lanalyse-de-la-variance.html"><a href="lanalyse-de-la-variance.html#les-boites-à-moustaches"><i class="fa fa-check"></i>Les boites à moustaches</a></li>
<li class="chapter" data-level="" data-path="lanalyse-de-la-variance.html"><a href="lanalyse-de-la-variance.html#application-de-lanova-à-un-facteur"><i class="fa fa-check"></i>Application de l’anova à un facteur</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/AODiakite/Data-Analysis" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Annalyse de données</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linearModel" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">1</span> Régression linéaire<a href="linearModel.html#linearModel" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-1" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Introduction<a href="linearModel.html#introduction-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La régression lineaire est une méthode statistique qui permet de trouver une relation lineaire entre des variables quantitives, une à expliquer et d’autres explicatives. C’est en fait un ajustement affine de la forme :</p>
<span class="math display">\[\begin{equation}
y_i = \beta_0 + \beta_1x_{i1} + \beta_2x_{i2} +\dots+\beta_px_{ip}+\epsilon_{i}\;\;
\end{equation}\]</span>
<p><span class="math display">\[i\in\{1,2,3\dots,n\}\]</span></p>
<ul>
<li><span class="math inline">\(y_i\)</span> représentent la <span class="math inline">\(i\)</span>ème valeur de la variable dépendantes <span class="math inline">\(y\)</span>.</li>
<li><span class="math inline">\(x_{ij}\)</span> représente la mesure de la <span class="math inline">\(i\)</span>ème observation de la variable explicative <span class="math inline">\(X_j\)</span></li>
<li>les <span class="math inline">\(\beta_j\)</span> sont les paramètres inconnus du modèle à estimer</li>
<li><span class="math inline">\(\epsilon_i\)</span> représente le bruit associé à la <span class="math inline">\(i\)</span>ème observation<br />
</li>
</ul>
<p>L’équation précédente peut être écrite sous une forme matricielle de cette manière :<br />
</p>
<span class="math display">\[\begin{equation}
y = X\beta +\epsilon
\end{equation}\]</span>
<p>avec :<br />
</p>
<span class="math display">\[\begin{equation}
y = \begin{pmatrix}y_1\\y_2\\\vdots\\y_n \end{pmatrix} \;\;
X = \begin{pmatrix}
   1 &amp; x_{11} &amp; x_{12} &amp; \dots &amp;x_{1p}\\
   1 &amp; x_{21} &amp; x_{22} &amp; \dots &amp;x_{2p}\\
   \vdots &amp;\vdots&amp;\vdots &amp; &amp;\vdots\\
   1 &amp; x_{n1} &amp; x_{n2} &amp; \dots &amp;x_{np}
   \end{pmatrix} \;\;
\beta = \begin{pmatrix}\beta_0\\
   \beta_1\\
   \vdots\\
   \beta_n \end{pmatrix} \;\;
\epsilon = \begin{pmatrix}
   \epsilon_1\\
   \epsilon_2\\
   \vdots\\
   \epsilon_n \end{pmatrix} \;\;
\end{equation}\]</span>
<p><br />
</p>
<p>Commençons par importer le jeu de données que nous nommerons <span class="math inline">\(dfcom\)</span>:<br />
</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="linearModel.html#cb1-1" aria-hidden="true" tabindex="-1"></a>Communities <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/Communities.csv&quot;</span>,<span class="at">row.names =</span> <span class="dv">1</span>)</span></code></pre></div>
<table>
<colgroup>
<col width="16%" />
<col width="4%" />
<col width="7%" />
<col width="9%" />
<col width="3%" />
<col width="4%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="5%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">communityname</th>
<th align="left">State</th>
<th align="left">countyCode</th>
<th align="left">communityCode</th>
<th align="right">fold</th>
<th align="right">pop</th>
<th align="right">perHoush</th>
<th align="right">pctBlack</th>
<th align="right">pctWhite</th>
<th align="right">pctAsian</th>
<th align="right">pctHisp</th>
<th align="right">pct12.21</th>
<th align="right">pct12.29</th>
<th align="right">pct16.24</th>
<th align="right">pct65up</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">BerkeleyHeightstownship</td>
<td align="left">NJ</td>
<td align="left">39</td>
<td align="left">5320</td>
<td align="right">1</td>
<td align="right">11980</td>
<td align="right">3.10</td>
<td align="right">1.37</td>
<td align="right">91.78</td>
<td align="right">6.50</td>
<td align="right">1.88</td>
<td align="right">12.47</td>
<td align="right">21.44</td>
<td align="right">10.93</td>
<td align="right">11.33</td>
</tr>
<tr class="even">
<td align="left">Marpletownship</td>
<td align="left">PA</td>
<td align="left">45</td>
<td align="left">47616</td>
<td align="right">1</td>
<td align="right">23123</td>
<td align="right">2.82</td>
<td align="right">0.80</td>
<td align="right">95.57</td>
<td align="right">3.44</td>
<td align="right">0.85</td>
<td align="right">11.01</td>
<td align="right">21.30</td>
<td align="right">10.48</td>
<td align="right">17.18</td>
</tr>
<tr class="odd">
<td align="left">Tigardcity</td>
<td align="left">OR</td>
<td align="left">?</td>
<td align="left">?</td>
<td align="right">1</td>
<td align="right">29344</td>
<td align="right">2.43</td>
<td align="right">0.74</td>
<td align="right">94.33</td>
<td align="right">3.43</td>
<td align="right">2.35</td>
<td align="right">11.36</td>
<td align="right">25.88</td>
<td align="right">11.01</td>
<td align="right">10.28</td>
</tr>
<tr class="even">
<td align="left">Gloversvillecity</td>
<td align="left">NY</td>
<td align="left">35</td>
<td align="left">29443</td>
<td align="right">1</td>
<td align="right">16656</td>
<td align="right">2.40</td>
<td align="right">1.70</td>
<td align="right">97.35</td>
<td align="right">0.50</td>
<td align="right">0.70</td>
<td align="right">12.55</td>
<td align="right">25.20</td>
<td align="right">12.19</td>
<td align="right">17.57</td>
</tr>
<tr class="odd">
<td align="left">Bemidjicity</td>
<td align="left">MN</td>
<td align="left">7</td>
<td align="left">5068</td>
<td align="right">1</td>
<td align="right">11245</td>
<td align="right">2.76</td>
<td align="right">0.53</td>
<td align="right">89.16</td>
<td align="right">1.17</td>
<td align="right">0.52</td>
<td align="right">24.46</td>
<td align="right">40.53</td>
<td align="right">28.69</td>
<td align="right">12.65</td>
</tr>
<tr class="even">
<td align="left">Springfieldcity</td>
<td align="left">MO</td>
<td align="left">?</td>
<td align="left">?</td>
<td align="right">1</td>
<td align="right">140494</td>
<td align="right">2.45</td>
<td align="right">2.51</td>
<td align="right">95.65</td>
<td align="right">0.90</td>
<td align="right">0.95</td>
<td align="right">18.09</td>
<td align="right">32.89</td>
<td align="right">20.04</td>
<td align="right">13.26</td>
</tr>
<tr class="odd">
<td align="left">Norwoodtown</td>
<td align="left">MA</td>
<td align="left">21</td>
<td align="left">50250</td>
<td align="right">1</td>
<td align="right">28700</td>
<td align="right">2.60</td>
<td align="right">1.60</td>
<td align="right">96.57</td>
<td align="right">1.47</td>
<td align="right">1.10</td>
<td align="right">11.17</td>
<td align="right">27.41</td>
<td align="right">12.76</td>
<td align="right">14.42</td>
</tr>
<tr class="even">
<td align="left">Andersoncity</td>
<td align="left">IN</td>
<td align="left">?</td>
<td align="left">?</td>
<td align="right">1</td>
<td align="right">59459</td>
<td align="right">2.45</td>
<td align="right">14.20</td>
<td align="right">84.87</td>
<td align="right">0.40</td>
<td align="right">0.63</td>
<td align="right">15.31</td>
<td align="right">27.93</td>
<td align="right">14.78</td>
<td align="right">14.60</td>
</tr>
<tr class="odd">
<td align="left">Fargocity</td>
<td align="left">ND</td>
<td align="left">17</td>
<td align="left">25700</td>
<td align="right">1</td>
<td align="right">74111</td>
<td align="right">2.46</td>
<td align="right">0.35</td>
<td align="right">97.11</td>
<td align="right">1.25</td>
<td align="right">0.73</td>
<td align="right">16.64</td>
<td align="right">35.16</td>
<td align="right">20.33</td>
<td align="right">8.58</td>
</tr>
<tr class="even">
<td align="left">Wacocity</td>
<td align="left">TX</td>
<td align="left">?</td>
<td align="left">?</td>
<td align="right">1</td>
<td align="right">103590</td>
<td align="right">2.62</td>
<td align="right">23.14</td>
<td align="right">67.60</td>
<td align="right">0.92</td>
<td align="right">16.35</td>
<td align="right">19.88</td>
<td align="right">34.55</td>
<td align="right">21.62</td>
<td align="right">13.12</td>
</tr>
</tbody>
</table>
</div>
<div id="application-de-la-régression-linéaire-simple" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Application de la régression linéaire simple<a href="linearModel.html#application-de-la-régression-linéaire-simple" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="corrélation" class="section level3 unnumbered hasAnchor">
<h3>Corrélation<a href="linearModel.html#corrélation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Comme nous l’avons mentionner dans l’introduction, le but de se projet est d’expliquer de différentes manières les meurtes aux USA. Par conséquent, on peut choisir comme variable dépendante, les crimes(<code>murders</code>) et chercher les variables explicatives. Dans le cas de le régression linéaire simple il doit exister une corrélation assez importante entre la variable <span class="math inline">\(y\)</span>(<code>muders</code>) et <span class="math inline">\(X\)</span> que nous recherchons actuellement. Donc commençons par filtrer les fortes corrélation avec la variable <span class="math inline">\(y\)</span> dans notre jeu de données.<br />
</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="linearModel.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation matrix</span></span>
<span id="cb2-2"><a href="linearModel.html#cb2-2" aria-hidden="true" tabindex="-1"></a>corCom <span class="ot">=</span> correlation<span class="sc">::</span><span class="fu">correlation</span>(Communities)</span>
<span id="cb2-3"><a href="linearModel.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtered correlation, bound =0.8</span></span>
<span id="cb2-4"><a href="linearModel.html#cb2-4" aria-hidden="true" tabindex="-1"></a>corCom[(corCom<span class="sc">$</span>r<span class="sc">&gt;</span><span class="fl">0.8</span>) <span class="sc">&amp;</span> corCom<span class="sc">$</span>Parameter2<span class="sc">==</span><span class="st">&#39;murders&#39;</span>,]</span></code></pre></div>
<pre><code>## # Correlation Matrix (pearson-method)
## 
## Parameter1       | Parameter2 |    r |       95% CI | t(2213) |         p
## -------------------------------------------------------------------------
## pop              |    murders | 0.96 | [0.96, 0.96] |  159.80 | &lt; .001***
## persUrban        |    murders | 0.96 | [0.95, 0.96] |  156.13 | &lt; .001***
## persPoverty      |    murders | 0.98 | [0.97, 0.98] |  211.42 | &lt; .001***
## kidsBornNevrMarr |    murders | 0.98 | [0.98, 0.98] |  221.27 | &lt; .001***
## numForeignBorn   |    murders | 0.89 | [0.88, 0.90] |   92.94 | &lt; .001***
## houseVacant      |    murders | 0.90 | [0.89, 0.90] |   95.29 | &lt; .001***
## persEmergShelt   |    murders | 0.89 | [0.88, 0.90] |   93.14 | &lt; .001***
## persHomeless     |    murders | 0.85 | [0.84, 0.86] |   76.49 | &lt; .001***
## 
## p-value adjustment method: Holm (1979)
## Observations: 2215</code></pre>
</div>
<div id="nuage-de-points" class="section level3 unnumbered hasAnchor">
<h3>Nuage de points<a href="linearModel.html#nuage-de-points" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Le tableau précédent indique les variables fortement corrélées avec notre <span class="math inline">\(output\)</span> <code>murders</code>. Prenons l’exemple de la variable <code>persPoverty</code> qui représente le nombre de personnes sous le seuil de pauvreté.<br />
</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="linearModel.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-2"><a href="linearModel.html#cb4-2" aria-hidden="true" tabindex="-1"></a>fig <span class="ot">=</span> <span class="fu">ggplot</span>(<span class="at">data =</span> Communities,<span class="fu">aes</span>(<span class="at">x=</span>persPoverty,<span class="at">y=</span>murders))<span class="sc">+</span></span>
<span id="cb4-3"><a href="linearModel.html#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb4-4"><a href="linearModel.html#cb4-4" aria-hidden="true" tabindex="-1"></a>fig</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="576" style="display: block; margin: auto;" /></p>
</div>
<div id="entraînement-de-modèle-droite-de-régression" class="section level3 unnumbered hasAnchor">
<h3>Entraînement de modèle &amp; Droite de régression<a href="linearModel.html#entraînement-de-modèle-droite-de-régression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La figure précédente laisse parraître qu’il pourrait effectivement exister une relation linéaire entre <code>murders</code> et <code>persPoverty</code>. Appliquons la fonction <code>lm()</code> pour voir ce qu’il en est vraiment ! Pour faire une analyse des résidus pltard, nous n’entrainerons que <span class="math inline">\(75\%\)</span> du jeu de données et le reste servira à la prédiction.<br />
</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="linearModel.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-2"><a href="linearModel.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Train_Test_Splite</span></span>
<span id="cb5-3"><a href="linearModel.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1345</span>)</span>
<span id="cb5-4"><a href="linearModel.html#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Pourcentage de donnees correspondant a 25%</span></span>
<span id="cb5-5"><a href="linearModel.html#cb5-5" aria-hidden="true" tabindex="-1"></a>per <span class="ot">=</span> <span class="fu">dim</span>(Communities)[<span class="dv">1</span>]<span class="sc">%/%</span><span class="dv">4</span></span>
<span id="cb5-6"><a href="linearModel.html#cb5-6" aria-hidden="true" tabindex="-1"></a>echantillon <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(Communities)[<span class="dv">1</span>]) <span class="sc">%&gt;%</span> .[<span class="dv">1</span><span class="sc">:</span>per]</span>
<span id="cb5-7"><a href="linearModel.html#cb5-7" aria-hidden="true" tabindex="-1"></a>lmDataTrain <span class="ot">=</span> Communities[<span class="sc">-</span>echantillon,<span class="fu">c</span>(<span class="st">&quot;murders&quot;</span>,<span class="st">&quot;persPoverty&quot;</span>)]</span>
<span id="cb5-8"><a href="linearModel.html#cb5-8" aria-hidden="true" tabindex="-1"></a>lmDataTest <span class="ot">=</span> Communities[echantillon,<span class="fu">c</span>(<span class="st">&quot;murders&quot;</span>,<span class="st">&quot;persPoverty&quot;</span>)]</span></code></pre></div>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="linearModel.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model Training</span></span>
<span id="cb6-2"><a href="linearModel.html#cb6-2" aria-hidden="true" tabindex="-1"></a>lmSimple <span class="ot">&lt;-</span> <span class="fu">lm</span>(murders<span class="sc">~</span>persPoverty,<span class="at">data =</span> lmDataTrain)</span>
<span id="cb6-3"><a href="linearModel.html#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmSimple)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = murders ~ persPoverty, data = lmDataTrain)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -136.43   -1.13    1.32    2.52  317.80 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.271e+00  3.340e-01  -9.796   &lt;2e-16 ***
## persPoverty  1.449e-03  7.447e-06 194.519   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.4 on 1660 degrees of freedom
## Multiple R-squared:  0.958,  Adjusted R-squared:  0.9579 
## F-statistic: 3.784e+04 on 1 and 1660 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>La sortie de la fonction <code>summary()</code> indique des <span class="math inline">\(p-values\)</span> très inférieures à <span class="math inline">\(5\%\)</span>, donc on rejette l’hypothèse de nullité des <span class="math inline">\(\beta\)</span>. On peut aussi constater que le coefficient de détermination <span class="math inline">\(R^2\)</span> vaut <span class="math inline">\(0.958\)</span> ce qui signifie que notre modèle a un score de <span class="math inline">\(95.8\%\)</span>. Ce dernier reflète une bonne qualité du modèle.<br />
</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="linearModel.html#cb8-1" aria-hidden="true" tabindex="-1"></a>ggstatsplot<span class="sc">::</span><span class="fu">ggscatterstats</span>(</span>
<span id="cb8-2"><a href="linearModel.html#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lmDataTrain, </span>
<span id="cb8-3"><a href="linearModel.html#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> persPoverty, </span>
<span id="cb8-4"><a href="linearModel.html#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> murders,</span>
<span id="cb8-5"><a href="linearModel.html#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab  =</span> <span class="st">&quot;le nombre de personnes sous le seuil de pauvreté&quot;</span>,</span>
<span id="cb8-6"><a href="linearModel.html#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab  =</span> <span class="st">&quot;le nombre de meurtres&quot;</span>,</span>
<span id="cb8-7"><a href="linearModel.html#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">&quot;Droite de régression&quot;</span>,</span>
<span id="cb8-8"><a href="linearModel.html#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">messages =</span> <span class="cn">FALSE</span></span>
<span id="cb8-9"><a href="linearModel.html#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;ggside&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
<div id="prédiction" class="section level3 unnumbered hasAnchor">
<h3>Prédiction<a href="linearModel.html#prédiction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A présent, nous pouvons utiliser notre échantillon non entrainé de données pour prédire à partir de notre model, quel aurait était le nombre de meurtres pour chauque <span class="math inline">\(x_i\)</span>.<br />
</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="linearModel.html#cb11-1" aria-hidden="true" tabindex="-1"></a>X_test<span class="ot">=</span><span class="fu">as.data.frame</span>(lmDataTest[[<span class="st">&quot;persPoverty&quot;</span>]])</span>
<span id="cb11-2"><a href="linearModel.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(X_test)<span class="ot">=</span><span class="st">&quot;persPoverty&quot;</span></span>
<span id="cb11-3"><a href="linearModel.html#cb11-3" aria-hidden="true" tabindex="-1"></a>y_predict <span class="ot">=</span> <span class="fu">predict</span>(<span class="at">object =</span> lmSimple,X_test)</span></code></pre></div>
</div>
<div id="graphes-des-résidus" class="section level3 unnumbered hasAnchor">
<h3>Graphes des résidus<a href="linearModel.html#graphes-des-résidus" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On peut représenter le graphe des <span class="math inline">\(\hat y\)</span> prédits et des <span class="math inline">\(y\)</span>. Pour un modèle parfait, le nuage de point doit être sur la première bissectrice.<br />
</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="linearModel.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span>lmDataTest) <span class="sc">+</span></span>
<span id="cb12-2"><a href="linearModel.html#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(persPoverty,murders),<span class="at">color =</span> <span class="st">&#39;darkgreen&#39;</span>,</span>
<span id="cb12-3"><a href="linearModel.html#cb12-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span><span class="dv">2</span>,<span class="at">shape=</span><span class="dv">22</span>,<span class="at">fill =</span><span class="st">&quot;darkgreen&quot;</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="linearModel.html#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> persPoverty, <span class="at">y =</span>y_predict), <span class="at">color =</span><span class="st">&#39;blue&#39;</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="linearModel.html#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span>persPoverty , </span>
<span id="cb12-6"><a href="linearModel.html#cb12-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> murders, <span class="at">xend =</span> persPoverty, <span class="at">yend =</span> y_predict),</span>
<span id="cb12-7"><a href="linearModel.html#cb12-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&#39;red&#39;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-13"></span>
<img src="_main_files/figure-html/unnamed-chunk-13-1.png" alt="Les segments en rouges représentent les résidus, les carrés verts les y non entrainés qui ont servi au test et les points bleus représentent les y prédits à partir de notre modèle." width="576" />
<p class="caption">
Figure 1.1: Les segments en rouges représentent les résidus, les carrés verts les y non entrainés qui ont servi au test et les points bleus représentent les y prédits à partir de notre modèle.
</p>
</div>
<p>On peut aussi visualiser la répartition des résidus du modèle <code>lmSimple</code> autour de leur moyenne <span class="math inline">\(0\)</span>.<br />
</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="linearModel.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lmSimple<span class="sc">$</span>residuals)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-14"></span>
<img src="_main_files/figure-html/unnamed-chunk-14-1.png" alt="On constate une répartition des résidus autour de 0" width="576" />
<p class="caption">
Figure 1.2: On constate une répartition des résidus autour de 0
</p>
</div>
</div>
</div>
<div id="application-de-la-régression-linéaire-multiple" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Application de la régression linéaire multiple<a href="linearModel.html#application-de-la-régression-linéaire-multiple" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dans cette partie on peut s’intéresser à la relation entre le nombre de meurtres et plusieurs autres variables. Un modèle de régression linéaire multiple pourrait faire l’affaire. Comme dans le cas de la régression linéaire simple, on va commencer par étudier la corrélation entre les variables explicatives. Nous allons choisir dans notre exemple, les variables qui sont corrélées avec <code>murders</code> comme varioles indépendantes.<br />
Ces dernières ne doivent pas être parfaitement corrélées entre elles. En effet dans la solution estimée du coefficient <span class="math inline">\(\beta\)</span>, on devra inversé la matrice X des variables explicatives. De ce fait une corrélation impliquera que la matrice ne soit pas de rang plein, donc non inversible.
<span class="math display">\[\hat\beta = (X&#39;X)^{-1}(X&#39;y)\]</span>
Commençons par selectionner nos variables pour la régression linéaire multiple.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="linearModel.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb14-2"><a href="linearModel.html#cb14-2" aria-hidden="true" tabindex="-1"></a>lmMultpleDF <span class="ot">=</span> Communities <span class="sc">%&gt;%</span> <span class="fu">select</span>(murders,pop, persUrban, persPoverty,</span>
<span id="cb14-3"><a href="linearModel.html#cb14-3" aria-hidden="true" tabindex="-1"></a>                           kidsBornNevrMarr, numForeignBorn,</span>
<span id="cb14-4"><a href="linearModel.html#cb14-4" aria-hidden="true" tabindex="-1"></a>                           houseVacant, persEmergShelt, persHomeless)</span></code></pre></div>
<div id="entraînement-de-modèle" class="section level3 unnumbered hasAnchor">
<h3>Entraînement de modèle<a href="linearModel.html#entraînement-de-modèle" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Le langage R permet d’entraîner le modèle linéaire multiple grâce à la fonction <code>lm()</code>. Pour indiquer à la fonction que nous sommes dans le cas d’une régression multiple, l’argument <code>formula()</code> doit recevoir <code>y~X1+X2+...+XP</code> et pour notre exemple <code>murders~pop+persUrban+...</code>.
Lors qu’on précise l’argument data de la fonction lm et que les données ne contiennent que les variables à étudier, l’argument formula peut dans ce cas recevoir juste <code>y~.</code>. En Pratique, pour notre jeu de données <code>lmMultpleDF</code>, voici le code approprié :</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="linearModel.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># train test split</span></span>
<span id="cb15-2"><a href="linearModel.html#cb15-2" aria-hidden="true" tabindex="-1"></a>lmMultiple_Test <span class="ot">=</span> lmMultpleDF[echantillon,]</span>
<span id="cb15-3"><a href="linearModel.html#cb15-3" aria-hidden="true" tabindex="-1"></a>lmMultiple_Train <span class="ot">=</span> lmMultpleDF[<span class="sc">-</span>echantillon,]</span>
<span id="cb15-4"><a href="linearModel.html#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model training</span></span>
<span id="cb15-5"><a href="linearModel.html#cb15-5" aria-hidden="true" tabindex="-1"></a>lmMultiple <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span>  murders<span class="sc">~</span>.,<span class="at">data =</span> lmMultiple_Train)</span>
<span id="cb15-6"><a href="linearModel.html#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmMultiple)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = murders ~ ., data = lmMultiple_Train)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -109.924   -1.099    0.412    1.206  175.748 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      -4.318e-01  3.698e-01  -1.168 0.243166    
## pop              -1.096e-04  3.312e-05  -3.310 0.000953 ***
## persUrban         1.071e-05  2.910e-05   0.368 0.713030    
## persPoverty       2.131e-04  6.680e-05   3.190 0.001452 ** 
## kidsBornNevrMarr  3.119e-03  1.196e-04  26.080  &lt; 2e-16 ***
## numForeignBorn    3.743e-04  1.809e-05  20.695  &lt; 2e-16 ***
## houseVacant       1.824e-03  1.338e-04  13.629  &lt; 2e-16 ***
## persEmergShelt    6.397e-03  1.853e-03   3.452 0.000571 ***
## persHomeless     -4.637e-02  4.110e-03 -11.282  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.41 on 1653 degrees of freedom
## Multiple R-squared:  0.9747, Adjusted R-squared:  0.9746 
## F-statistic:  7972 on 8 and 1653 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>La sortie de la fonction <code>summary()</code> indique qu’on peut se passer de la variable <code>persUrban</code> dans l’explication de <code>murders</code> par un modèle linéaire. En effet, son coefficient <span class="math inline">\(\beta\)</span> pourrait être nul car les <span class="math inline">\(p-values\)</span> est supérieure à <span class="math inline">\(\alpha=5\%\)</span>.<br />
</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="linearModel.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb17-2"><a href="linearModel.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Train test split</span></span>
<span id="cb17-3"><a href="linearModel.html#cb17-3" aria-hidden="true" tabindex="-1"></a>lmMultpleDF <span class="ot">=</span> lmMultpleDF <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>persUrban)</span>
<span id="cb17-4"><a href="linearModel.html#cb17-4" aria-hidden="true" tabindex="-1"></a>lmMultiple_Test <span class="ot">=</span> lmMultpleDF[echantillon,]</span>
<span id="cb17-5"><a href="linearModel.html#cb17-5" aria-hidden="true" tabindex="-1"></a>lmMultiple_Train <span class="ot">=</span> lmMultpleDF[<span class="sc">-</span>echantillon,]</span>
<span id="cb17-6"><a href="linearModel.html#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Model training</span></span>
<span id="cb17-7"><a href="linearModel.html#cb17-7" aria-hidden="true" tabindex="-1"></a>lmMultiple <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span>  murders<span class="sc">~</span>.,<span class="at">data =</span> lmMultiple_Train)</span>
<span id="cb17-8"><a href="linearModel.html#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmMultiple)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = murders ~ ., data = lmMultiple_Train)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -110.080   -1.137    0.422    1.222  175.907 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      -5.027e-01  3.155e-01  -1.593 0.111255    
## pop              -9.813e-05  1.092e-05  -8.983  &lt; 2e-16 ***
## persPoverty       2.098e-04  6.619e-05   3.170 0.001555 ** 
## kidsBornNevrMarr  3.122e-03  1.194e-04  26.150  &lt; 2e-16 ***
## numForeignBorn    3.739e-04  1.804e-05  20.720  &lt; 2e-16 ***
## houseVacant       1.822e-03  1.337e-04  13.630  &lt; 2e-16 ***
## persEmergShelt    6.371e-03  1.851e-03   3.441 0.000593 ***
## persHomeless     -4.644e-02  4.105e-03 -11.312  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.41 on 1654 degrees of freedom
## Multiple R-squared:  0.9747, Adjusted R-squared:  0.9746 
## F-statistic:  9116 on 7 and 1654 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>De plus, le coefficient d’ajustement <span class="math inline">\(R^2\)</span> est de <span class="math inline">\(0.9747\)</span>, soit un score de <span class="math inline">\(97.47\%\)</span> pour notre modèle ce qui est un très bon résultat.</p>
</div>
<div id="graphes-de-régression" class="section level3 unnumbered hasAnchor">
<h3>Graphes de régression<a href="linearModel.html#graphes-de-régression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Lorsque le nombre de variables explicatives dépasse <span class="math inline">\(2\)</span>, il est impossible de représenter sur un même graphes le nuage de points formé par y. En effet la dimension physique maximale est de 3.
Il existe plusieurs packages qui donnent des représentations assez significatives en deux dimensions du modèle linéaire multiple tel que <code>car</code><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>.<br />
La représentation de la droite de régression peut se faire sur chaque dimension des variables explicatives grâce à la fonction <code>avPlots()</code> de la librairie <code>car</code>.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="linearModel.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb19-2"><a href="linearModel.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(lmMultiple)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
<div id="prédiction-1" class="section level3 unnumbered hasAnchor">
<h3>Prédiction<a href="linearModel.html#prédiction-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La prédiction dans le modèle linéaire multiple se fait aussi avec la fonction <code>predict()</code> comme dans le cas simple. On va utiliser notre modèle déjà entraîné avec <span class="math inline">\(75\%\)</span> de notre jeu de données <code>lmMultpleDF</code> et les <span class="math inline">\(20\%\)</span> pour effectuer une prédiction. Cela peut nous permettre de voir les résidus entre les valeurs prédites et les valeurs réelles de <span class="math inline">\(y\)</span>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="linearModel.html#cb20-1" aria-hidden="true" tabindex="-1"></a>y_hat <span class="ot">=</span> <span class="fu">predict</span>(lmMultiple,lmMultiple_Test[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb20-2"><a href="linearModel.html#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(y_hat,<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##       2037        174        210        683        821        519       1593 
##  0.2445685 19.3517750  1.4280286  5.4097354  7.8093372  0.8155394 -1.6654378 
##       1098       1266       1153 
##  1.5812592 -1.1213912 -0.7649363</code></pre>
</div>
<div id="graphe-des-résidus" class="section level3 hasAnchor" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Graphe des résidus<a href="linearModel.html#graphe-des-résidus" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On peut visualiser les résidus entre les variables <span class="math inline">\(y_i\)</span> observés et les <span class="math inline">\(\hat y_i\)</span> prédites :</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="linearModel.html#cb22-1" aria-hidden="true" tabindex="-1"></a>y_test <span class="ot">=</span> lmMultiple_Test<span class="sc">$</span>murders</span>
<span id="cb22-2"><a href="linearModel.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb22-3"><a href="linearModel.html#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> y_test, <span class="at">y =</span> y_hat)) <span class="sc">+</span></span>
<span id="cb22-4"><a href="linearModel.html#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span><span class="st">&#39;blue&#39;</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="linearModel.html#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span>y_test , </span>
<span id="cb22-6"><a href="linearModel.html#cb22-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y =</span> y_test, <span class="at">xend =</span> y_test, <span class="at">yend =</span> y_hat),</span>
<span id="cb22-7"><a href="linearModel.html#cb22-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&#39;red&#39;</span>) <span class="sc">+</span></span>
<span id="cb22-8"><a href="linearModel.html#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Predicted murders&quot;</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">&quot;Murders&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-20"></span>
<img src="_main_files/figure-html/unnamed-chunk-20-1.png" alt="Les résidus sont assez proches de 0 cela  reflète la bonne qualité du modèle." width="672" />
<p class="caption">
Figure 1.3: Les résidus sont assez proches de 0 cela reflète la bonne qualité du modèle.
</p>
</div>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>package car : <a href="https://cran.r-project.org/web/packages/car/index.html" class="uri">https://cran.r-project.org/web/packages/car/index.html</a><a href="linearModel.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="principal-component-analysis-and-factor-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/AODiakite/Data-Analysis/edit/main/02-LinearModel.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
